[package]
name = "text2art"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "Simple library for translate text to ascii art."
repository = "https://github.com/follow39/text2art"
keywords = ["cli"]

[dependencies]
regex = "1.10.*"
unicode-segmentation = "1.10.*"
